<?php
/**
 * Plugin Name: Evalnor Talent
 * Description: Operational WordPress adapter for Evalnor Talent.
 * Version: 0.5.0
 * Requires PHP: 8.1
 * Text Domain: talent
 */
declare(strict_types=1);
defined('ABSPATH')||exit;
define('EVALNOR_TALENT_VERSION','0.5.0');define('EVALNOR_TALENT_OPTION','evalnor_talent_records_v2');define('EVALNOR_TALENT_AUDIT','evalnor_talent_audit_v1');
register_activation_hook(__FILE__,static function():void{$r=get_role('administrator');if($r)$r->add_cap('evalnor_manage_talent');if(get_option(EVALNOR_TALENT_OPTION,null)===null)add_option(EVALNOR_TALENT_OPTION,[],'',false);update_option('evalnor_talent_schema',2,false);});
function evalnor_talent_can():bool{return current_user_can('evalnor_manage_talent')||current_user_can('evalnor_manage_business')||current_user_can('manage_options');}
function evalnor_talent_rows():array{$v=get_option(EVALNOR_TALENT_OPTION,[]);return is_array($v)?array_values($v):[];}
function evalnor_talent_audit(string $action,string $id):void{$a=get_option(EVALNOR_TALENT_AUDIT,[]);if(!is_array($a))$a=[];array_unshift($a,['at'=>gmdate('c'),'user'=>get_current_user_id(),'action'=>$action,'id'=>$id]);update_option(EVALNOR_TALENT_AUDIT,array_slice($a,0,500),false);}
function evalnor_talent_clean(array $in):array{$out=['id'=>sanitize_key((string)($in['id']??wp_generate_uuid4())),'created_at'=>sanitize_text_field((string)($in['created_at']??gmdate('c'))),'updated_at'=>gmdate('c')];$out['name']=sanitize_text_field((string)($in['name']??''));$out['email']=sanitize_text_field((string)($in['email']??''));$out['job']=sanitize_text_field((string)($in['job']??''));$out['status']=sanitize_key((string)($in['status']??'new'));if(!in_array($out['status'],['new','screening','interview','offer','hired'],true))$out['status']='new';return $out;}
function evalnor_talent_upsert(array $row):array{$all=evalnor_talent_rows();$found=false;foreach($all as $i=>$old)if(($old['id']??'')===$row['id']){$row['created_at']=$old['created_at']??$row['created_at'];$all[$i]=$row;$found=true;break;}if(!$found)$all[]=$row;update_option(EVALNOR_TALENT_OPTION,$all,false);evalnor_talent_audit($found?'update':'create',$row['id']);return $row;}
function evalnor_talent_delete(string $id):bool{$all=evalnor_talent_rows();$new=array_values(array_filter($all,static fn($r)=>(string)($r['id']??'')!==$id));if(count($new)===count($all))return false;update_option(EVALNOR_TALENT_OPTION,$new,false);evalnor_talent_audit('delete',$id);return true;}
add_action('admin_menu',static function():void{add_menu_page('Evalnor Talent','Evalnor Talent','evalnor_manage_talent','talent','evalnor_talent_screen','dashicons-chart-area',58);});
function evalnor_talent_screen():void{if(!evalnor_talent_can())wp_die('Access denied');if(isset($_POST['evalnor_action'])&&check_admin_referer('evalnor_talent_save')){if($_POST['evalnor_action']==='save')evalnor_talent_upsert(evalnor_talent_clean(wp_unslash($_POST)));if($_POST['evalnor_action']==='delete')evalnor_talent_delete(sanitize_key((string)($_POST['id']??'')));} $rows=evalnor_talent_rows();$counts=[];foreach(['new','screening','interview','offer','hired'] as $s)$counts[$s]=0;foreach($rows as $r)if(isset($counts[$r['status']??'']))$counts[$r['status']]++;echo '<div class="wrap"><h1>Evalnor Talent <small>v'.esc_html(EVALNOR_TALENT_VERSION).'</small></h1><p>';foreach($counts as $s=>$n)echo '<strong>'.esc_html($s).':</strong> '.esc_html((string)$n).' &nbsp; ';echo '</p><h2>Ajouter — Candidat</h2><form method="post">';wp_nonce_field('evalnor_talent_save');echo '<input type="hidden" name="evalnor_action" value="save"><table class="form-table">';echo '<tr><th>Nom</th><td><input class="regular-text" name="name" required></td></tr>';echo '<tr><th>Courriel</th><td><input class="regular-text" name="email" required></td></tr>';echo '<tr><th>Poste</th><td><input class="regular-text" name="job" required></td></tr>';echo '<tr><th>Statut</th><td><select name="status">';foreach(['new','screening','interview','offer','hired'] as $s)echo '<option>'.esc_html($s).'</option>';echo '</select></td></tr></table><p><button class="button button-primary">Enregistrer</button></p></form><h2>Candidats</h2><table class="widefat striped"><thead><tr><th>Nom</th><th>Courriel</th><th>Poste</th><th>Statut</th><th>Action</th></tr></thead><tbody>';foreach($rows as $r){echo '<tr><td>'.esc_html((string)($r['name']??'')).'</td><td>'.esc_html((string)($r['email']??'')).'</td><td>'.esc_html((string)($r['job']??'')).'</td><td>'.esc_html((string)($r['status']??'')).'</td><td><form method="post">';wp_nonce_field('evalnor_talent_save');echo '<input type="hidden" name="evalnor_action" value="delete"><input type="hidden" name="id" value="'.esc_attr((string)$r['id']).'"><button class="button">Supprimer</button></form></td></tr>';}echo '</tbody></table><p><a class="button" href="'.esc_url(rest_url('evalnor/talent/v1/export')).'">Export JSON</a></p></div>';}
add_action('rest_api_init',static function():void{
 $perm='evalnor_talent_can';register_rest_route('evalnor/talent/v1','/health',['methods'=>'GET','permission_callback'=>$perm,'callback'=>static fn()=>rest_ensure_response(['product'=>'talent','version'=>EVALNOR_TALENT_VERSION,'status'=>'operational','records'=>count(evalnor_talent_rows()),'schema'=>2])]);
 register_rest_route('evalnor/talent/v1','/records',['methods'=>'GET','permission_callback'=>$perm,'callback'=>static fn()=>rest_ensure_response(evalnor_talent_rows())]);
 register_rest_route('evalnor/talent/v1','/records',['methods'=>'POST','permission_callback'=>$perm,'callback'=>static function(WP_REST_Request $q){$d=$q->get_json_params();return is_array($d)?rest_ensure_response(evalnor_talent_upsert(evalnor_talent_clean($d))):new WP_Error('invalid','Invalid payload',['status'=>400]);}]);
 register_rest_route('evalnor/talent/v1','/records/(?P<id>[a-zA-Z0-9_-]+)',['methods'=>'DELETE','permission_callback'=>$perm,'callback'=>static fn(WP_REST_Request $q)=>rest_ensure_response(['deleted'=>evalnor_talent_delete(sanitize_key($q['id']))])]);
 register_rest_route('evalnor/talent/v1','/export',['methods'=>'GET','permission_callback'=>$perm,'callback'=>static fn()=>rest_ensure_response(['schema'=>'evalnor.talent/v2','version'=>EVALNOR_TALENT_VERSION,'exported_at'=>gmdate('c'),'records'=>evalnor_talent_rows()])]);
 register_rest_route('evalnor/talent/v1','/import',['methods'=>'POST','permission_callback'=>$perm,'callback'=>static function(WP_REST_Request $q){$d=$q->get_json_params();if(!is_array($d)||!isset($d['records'])||!is_array($d['records']))return new WP_Error('invalid_import','Invalid import',['status'=>400]);$n=0;foreach($d['records'] as $r)if(is_array($r)){evalnor_talent_upsert(evalnor_talent_clean($r));$n++;}return rest_ensure_response(['imported'=>$n]);}]);
});
add_filter('evalnor_app_home',static fn(string $url):string=>evalnor_talent_can()?admin_url('admin.php?page=talent'):$url);
